dist: xenial
language: python
services:
  - xvfb
python:
  - "3.6"
before_install:
 - sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
 - sudo apt-get install qt5-default qttools5-dev-tools
install:
  - cur=`pwd`
  # Pull CoppeliaSim
  - wget http://www.coppeliarobotics.com/files/CoppeliaSim_Edu_V4_1_0_Ubuntu16_04.tar.xz
  - tar -xf CoppeliaSim_Edu_V4_1_0_Ubuntu16_04.tar.xz
  - export COPPELIASIM_ROOT="$cur/CoppeliaSim_Edu_V4_1_0_Ubuntu16_04"
  - echo $COPPELIASIM_ROOT
  # COPPELIASIM_ROOT/platforms needed otherwise will get:
  # qt.qpa.plugin: Could not load the Qt platform plugin "xcb"
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$COPPELIASIM_ROOT:$COPPELIASIM_ROOT/platforms
  - export QT_QPA_PLATFORM_PLUGIN_PATH=$COPPELIASIM_ROOT
  - pip3 install -r requirements.txt
  - pip3 install .
# command to run tests
script:
  - pip3 install mypy
  - mypy --ignore-missing-imports -p pyrep
  # We need to rename the local folder otherwise we will test this rather than
  # the installed version.
  - mv pyrep _pyrep
  - python3 -m unittest discover tests
