#constants
#Scene object types. Values are serialized
sim_object_shape_type           =0
sim_object_joint_type           =1
sim_object_graph_type           =2
sim_object_camera_type          =3
sim_object_dummy_type           =4
sim_object_proximitysensor_type =5
sim_object_reserved1            =6
sim_object_reserved2            =7
sim_object_path_type            =8
sim_object_visionsensor_type    =9
sim_object_volume_type          =10
sim_object_mill_type            =11
sim_object_forcesensor_type     =12
sim_object_light_type           =13
sim_object_mirror_type          =14

#General object types. Values are serialized
sim_appobj_object_type          =109
sim_appobj_collision_type       =110
sim_appobj_distance_type        =111
sim_appobj_simulation_type      =112
sim_appobj_ik_type              =113
sim_appobj_constraintsolver_type=114
sim_appobj_collection_type      =115
sim_appobj_ui_type              =116
sim_appobj_script_type          =117
sim_appobj_pathplanning_type    =118
sim_appobj_RESERVED_type        =119
sim_appobj_texture_type         =120

# Ik calculation methods. Values are serialized
sim_ik_pseudo_inverse_method        =0
sim_ik_damped_least_squares_method  =1
sim_ik_jacobian_transpose_method    =2

# Ik constraints. Values are serialized
sim_ik_x_constraint         =1
sim_ik_y_constraint         =2
sim_ik_z_constraint         =4
sim_ik_alpha_beta_constraint=8
sim_ik_gamma_constraint     =16
sim_ik_avoidance_constraint =64

# Ik calculation results 
sim_ikresult_not_performed  =0
sim_ikresult_success        =1
sim_ikresult_fail           =2

# Scene object sub-types. Values are serialized 
# Light sub-types 
sim_light_omnidirectional_subtype   =1
sim_light_spot_subtype              =2
sim_light_directional_subtype       =3
# Joint sub-types 
sim_joint_revolute_subtype          =10
sim_joint_prismatic_subtype         =11
sim_joint_spherical_subtype         =12
# Shape sub-types 
sim_shape_simpleshape_subtype       =20
sim_shape_multishape_subtype        =21
# Proximity sensor sub-types 
sim_proximitysensor_pyramid_subtype =30
sim_proximitysensor_cylinder_subtype=31
sim_proximitysensor_disc_subtype    =32
sim_proximitysensor_cone_subtype    =33
sim_proximitysensor_ray_subtype     =34
# Mill sub-types 
sim_mill_pyramid_subtype            =40
sim_mill_cylinder_subtype           =41
sim_mill_disc_subtype               =42
sim_mill_cone_subtype               =42
# No sub-type 
sim_object_no_subtype               =200


#Scene object main properties (serialized)
sim_objectspecialproperty_collidable                    =0x0001
sim_objectspecialproperty_measurable                    =0x0002
#reserved                        =0x0004 
#reserved                        =0x0008 
sim_objectspecialproperty_detectable_ultrasonic            =0x0010
sim_objectspecialproperty_detectable_infrared            =0x0020
sim_objectspecialproperty_detectable_laser                =0x0040
sim_objectspecialproperty_detectable_inductive            =0x0080
sim_objectspecialproperty_detectable_capacitive            =0x0100
sim_objectspecialproperty_renderable                    =0x0200
sim_objectspecialproperty_detectable_all =sim_objectspecialproperty_detectable_ultrasonic|sim_objectspecialproperty_detectable_infrared|sim_objectspecialproperty_detectable_laser|sim_objectspecialproperty_detectable_inductive|sim_objectspecialproperty_detectable_capacitive
sim_objectspecialproperty_cuttable                        =0x0400
sim_objectspecialproperty_pathplanning_ignored            =0x0800

# Model properties (serialized)
sim_modelproperty_not_collidable                =0x0001
sim_modelproperty_not_measurable                =0x0002
sim_modelproperty_not_renderable                =0x0004
sim_modelproperty_not_detectable                =0x0008
sim_modelproperty_not_cuttable                    =0x0010
sim_modelproperty_not_dynamic                    =0x0020
sim_modelproperty_not_respondable                =0x0040 # cannot be selected if sim_modelproperty_not_dynamic is not selected 
sim_modelproperty_not_reset                        =0x0080 # Model is not reset at simulation end. This flag is cleared at simulation end 
sim_modelproperty_not_visible                    =0x0100 # Whole model is invisible independent of local visibility settings 
sim_modelproperty_not_model                        =0xf000 # object is not a model 


# Check the documentation instead of comments below!! 
# Following messages are dispatched to the Lua-message container 
sim_message_ui_button_state_change  =0    # a UI button slider etc. changed (due to a user's action). aux[0]=UI handle aux[1]=button handle aux[2]=button attributes aux[3]=slider position (if slider) 
sim_message_reserved9               =1    # Do not use 
sim_message_object_selection_changed=2
sim_message_reserved10                =3    # do not use 
sim_message_model_loaded            =4
sim_message_reserved11                =5    # do not use 
sim_message_keypress                =6    # a key was pressed while the focus was on a page (aux[0]=key aux[1]=ctrl and shift key state) 
sim_message_bannerclicked            =7    # a banner was clicked (aux[0]=banner ID) 


# Following messages are dispatched only to the C-API (not available from Lua) 
sim_message_for_c_api_only_start        =0x100      # Do not use 
sim_message_reserved1                   =0x101      # Do not use 
sim_message_reserved2                    =0x102      # Do not use 
sim_message_reserved3                    =0x103      # Do not use 
sim_message_eventcallback_scenesave        =0x104        # about to save a scene 
sim_message_eventcallback_modelsave        =0x105      # about to save a model (current selection will be saved) 
sim_message_eventcallback_moduleopen    =0x106        # called when simOpenModule in Lua is called 
sim_message_eventcallback_modulehandle    =0x107        # called when simHandleModule in Lua is called with argument false 
sim_message_eventcallback_moduleclose    =0x108        # called when simCloseModule in Lua is called 
sim_message_reserved4                    =0x109      # Do not use 
sim_message_reserved5                    =0x10a        # Do not use 
sim_message_reserved6                    =0x10b        # Do not use 
sim_message_reserved7                    =0x10c        # Do not use 
sim_message_eventcallback_instancepass    =0x10d        # Called once every main application loop pass. auxiliaryData[0] contains event flags of events that happened since last time 
sim_message_eventcallback_broadcast     =0x10e
sim_message_eventcallback_imagefilter_enumreset =0x10f
sim_message_eventcallback_imagefilter_enumerate      =0x110
sim_message_eventcallback_imagefilter_adjustparams   =0x111
sim_message_eventcallback_imagefilter_reserved       =0x112
sim_message_eventcallback_imagefilter_process        =0x113
sim_message_eventcallback_reserved1                  =0x114   # do not use 
sim_message_eventcallback_reserved2                  =0x115   # do not use 
sim_message_eventcallback_reserved3                  =0x116   # do not use 
sim_message_eventcallback_reserved4                  =0x117   # do not use 
sim_message_eventcallback_abouttoundo                 =0x118   # the undo button was hit and a previous state is about to be restored 
sim_message_eventcallback_undoperformed                 =0x119   # the undo button was hit and a previous state restored 
sim_message_eventcallback_abouttoredo                 =0x11a   # the redo button was hit and a future state is about to be restored  
sim_message_eventcallback_redoperformed                 =0x11b   # the redo button was hit and a future state restored  
sim_message_eventcallback_scripticondblclick         =0x11c   # scipt icon was double clicked.  (aux[0]=object handle associated with script set replyData[0] to 1 if script should not be opened)  
sim_message_eventcallback_simulationabouttostart     =0x11d
sim_message_eventcallback_simulationended            =0x11e
sim_message_eventcallback_reserved5                     =0x11f   # do not use 
sim_message_eventcallback_keypress                     =0x120   # a key was pressed while the focus was on a page (aux[0]=key aux[1]=ctrl and shift key state) 
sim_message_eventcallback_modulehandleinsensingpart  =0x121   # called when simHandleModule in Lua is called with argument true 
sim_message_eventcallback_renderingpass              =0x122   # called just before the scene is rendered 
sim_message_eventcallback_bannerclicked              =0x123   # called when a banner was clicked (aux[0]=banner ID) 
sim_message_eventcallback_menuitemselected           =0x124   # auxiliaryData[0] indicates the handle of the item auxiliaryData[1] indicates the state of the item 
sim_message_eventcallback_refreshdialogs             =0x125   # aux[0]=refresh degree (0=light 1=medium 2=full) 
sim_message_eventcallback_sceneloaded                =0x126
sim_message_eventcallback_modelloaded                =0x127
sim_message_eventcallback_instanceswitch             =0x128
sim_message_eventcallback_guipass                    =0x129
sim_message_eventcallback_mainscriptabouttobecalled  =0x12a
sim_message_eventcallback_rmlposition                =0x12b   #the command simRMLPosition was called. The appropriate plugin should handle the call
sim_message_eventcallback_rmlvelocity                =0x12c   # the command simRMLVelocity was called. The appropriate plugin should handle the call
sim_message_simulation_start_resume_request          =0x1000
sim_message_simulation_pause_request                 =0x1001
sim_message_simulation_stop_request                  =0x1002

# Scene object properties. Combine with the | operator 
sim_objectproperty_reserved1                =0x0000
sim_objectproperty_reserved2                =0x0001
sim_objectproperty_reserved3                =0x0002
sim_objectproperty_reserved4                =0x0003
sim_objectproperty_reserved5                =0x0004 # formely sim_objectproperty_visible 
sim_objectproperty_reserved6                =0x0008 # formely sim_objectproperty_wireframe 
sim_objectproperty_collapsed                =0x0010
sim_objectproperty_selectable                =0x0020
sim_objectproperty_reserved7                =0x0040
sim_objectproperty_selectmodelbaseinstead    =0x0080
sim_objectproperty_dontshowasinsidemodel    =0x0100
# reserved                                    =0x0200 
sim_objectproperty_canupdatedna                =0x0400
sim_objectproperty_selectinvisible            =0x0800
sim_objectproperty_depthinvisible            =0x1000


# type of arguments (input and output) for custom lua commands 
sim_lua_arg_nil     =0
sim_lua_arg_bool    =1    
sim_lua_arg_int     =2
sim_lua_arg_float   =3
sim_lua_arg_string  =4
sim_lua_arg_invalid =5
sim_lua_arg_table   =8

# custom user interface properties. Values are serialized. 
sim_ui_property_visible                        =0x0001
sim_ui_property_visibleduringsimulationonly    =0x0002
sim_ui_property_moveable                    =0x0004
sim_ui_property_relativetoleftborder        =0x0008
sim_ui_property_relativetotopborder            =0x0010
sim_ui_property_fixedwidthfont                =0x0020
sim_ui_property_systemblock                    =0x0040
sim_ui_property_settocenter                    =0x0080
sim_ui_property_rolledup                    =0x0100
sim_ui_property_selectassociatedobject        =0x0200
sim_ui_property_visiblewhenobjectselected    =0x0400


# button properties. Values are serialized. 
sim_buttonproperty_button                =0x0000
sim_buttonproperty_label                =0x0001
sim_buttonproperty_slider                =0x0002
sim_buttonproperty_editbox                =0x0003
sim_buttonproperty_staydown                =0x0008
sim_buttonproperty_enabled                =0x0010
sim_buttonproperty_borderless            =0x0020
sim_buttonproperty_horizontallycentered    =0x0040
sim_buttonproperty_ignoremouse            =0x0080
sim_buttonproperty_isdown                =0x0100
sim_buttonproperty_transparent            =0x0200
sim_buttonproperty_nobackgroundcolor    =0x0400
sim_buttonproperty_rollupaction            =0x0800
sim_buttonproperty_closeaction            =0x1000
sim_buttonproperty_verticallycentered    =0x2000
sim_buttonproperty_downupevent            =0x4000


# Simulation status 
sim_simulation_stopped                        =0x00                                # Simulation is stopped 
sim_simulation_paused                        =0x08                                # Simulation is paused 
sim_simulation_advancing                    =0x10                                # Simulation is advancing 
sim_simulation_advancing_firstafterstop        =sim_simulation_advancing|0x00        # First simulation pass (1x) 
sim_simulation_advancing_running            =sim_simulation_advancing|0x01        # Normal simulation pass (>=1x) 
# reserved                                    =sim_simulation_advancing|0x02 
sim_simulation_advancing_lastbeforepause    =sim_simulation_advancing|0x03        # Last simulation pass before pause (1x) 
sim_simulation_advancing_firstafterpause    =sim_simulation_advancing|0x04        # First simulation pass after pause (1x) 
sim_simulation_advancing_abouttostop        =sim_simulation_advancing|0x05        # "Trying to stop" simulation pass (>=1x) 
sim_simulation_advancing_lastbeforestop        =sim_simulation_advancing|0x06        # Last simulation pass (1x) 


# Script execution result (first return value) 
sim_script_no_error                    =0
sim_script_main_script_nonexistent    =1
sim_script_main_script_not_called    =2
sim_script_reentrance_error            =4
sim_script_lua_error                =8
sim_script_call_error                =16


 # Script types (serialized!) 
sim_scripttype_mainscript   =0
sim_scripttype_childscript  =1
sim_scripttype_jointctrlcallback  =4
sim_scripttype_contactcallback  =5
sim_scripttype_customizationscript  =6
sim_scripttype_generalcallback  =7

# API call error messages 
sim_api_errormessage_ignore    =0    # does not memorize nor output errors 
sim_api_errormessage_report    =1    # memorizes errors (default for C-API calls) 
sim_api_errormessage_output    =2  # memorizes and outputs errors (default for Lua-API calls) 


# special argument of some functions 
sim_handle_all                        =-2
sim_handle_all_except_explicit        =-3
sim_handle_self                        =-4
sim_handle_main_script                =-5
sim_handle_tree                        =-6
sim_handle_chain                    =-7
sim_handle_single                    =-8
sim_handle_default                    =-9
sim_handle_all_except_self            =-10
sim_handle_parent                    =-11


# special handle flags
sim_handleflag_assembly                =0x400000
sim_handleflag_model                =0x800000


# distance calculation methods (serialized) 
sim_distcalcmethod_dl               =0
sim_distcalcmethod_dac              =1
sim_distcalcmethod_max_dl_dac       =2
sim_distcalcmethod_dl_and_dac       =3
sim_distcalcmethod_sqrt_dl2_and_dac2=4
sim_distcalcmethod_dl_if_nonzero    =5
sim_distcalcmethod_dac_if_nonzero   =6


 # Generic dialog styles 
sim_dlgstyle_message        =0
sim_dlgstyle_input          =1
sim_dlgstyle_ok             =2
sim_dlgstyle_ok_cancel      =3
sim_dlgstyle_yes_no         =4
sim_dlgstyle_dont_center    =32# can be combined with one of above values. Only with this flag can the position of the related UI be set just after dialog creation  

 # Generic dialog return values 
sim_dlgret_still_open   =0
sim_dlgret_ok           =1
sim_dlgret_cancel       =2
sim_dlgret_yes          =3
sim_dlgret_no           =4


# Path properties 
sim_pathproperty_show_line                            =0x0001
sim_pathproperty_show_orientation                    =0x0002
sim_pathproperty_closed_path                        =0x0004
sim_pathproperty_automatic_orientation                =0x0008
sim_pathproperty_invert_velocity                    =0x0010
sim_pathproperty_infinite_acceleration                =0x0020
sim_pathproperty_flat_path                            =0x0040
sim_pathproperty_show_position                        =0x0080
sim_pathproperty_auto_velocity_profile_translation    =0x0100
sim_pathproperty_auto_velocity_profile_rotation        =0x0200
sim_pathproperty_endpoints_at_zero                    =0x0400
sim_pathproperty_keep_x_up                            =0x0800


 # drawing objects 
# following are mutually exclusive 
sim_drawing_points          =0            # 3 values per point (point size in pixels) 
sim_drawing_lines            =1            # 6 values per line (line size in pixels) 
sim_drawing_triangles        =2            # 9 values per triangle 
sim_drawing_trianglepoints    =3            # 6 values per point (3 for triangle position 3 for triangle normal vector) (triangle size in meters) 
sim_drawing_quadpoints        =4            # 6 values per point (3 for quad position 3 for quad normal vector) (quad size in meters) 
sim_drawing_discpoints        =5            # 6 values per point (3 for disc position 3 for disc normal vector) (disc size in meters) 
sim_drawing_cubepoints        =6          # 6 values per point (3 for cube position 3 for cube normal vector) (cube size in meters) 
sim_drawing_spherepoints    =7          # 3 values per point (sphere size in meters) 

# following can be or-combined 
sim_drawing_itemcolors                =0x00020 # +3 values per item (each item has its own ambient color (rgb values)).
                                             # Mutually exclusive with sim_drawing_vertexcolors 
sim_drawing_vertexcolors            =0x00040 # +3 values per vertex (each vertex has its own ambient color (rgb values). Only for sim_drawing_lines (+6) and for sim_drawing_triangles(+9)). Mutually exclusive with sim_drawing_itemcolors 
sim_drawing_itemsizes                =0x00080 # +1 value per item (each item has its own size). Not for sim_drawing_triangles 
sim_drawing_backfaceculling            =0x00100 # back faces are not displayed for all items 
sim_drawing_wireframe                =0x00200 # all items displayed in wireframe 
sim_drawing_painttag                =0x00400 # all items are tagged as paint (for additinal processing at a later stage) 
sim_drawing_followparentvisibility    =0x00800 # if the object is associated with a scene object then it follows that visibility otherwise it is always visible 
sim_drawing_cyclic                    =0x01000 # if the max item count was reached then the first items are overwritten. 
sim_drawing_50percenttransparency    =0x02000 # the drawing object will be 50% transparent 
sim_drawing_25percenttransparency    =0x04000 # the drawing object will be 25% transparent 
sim_drawing_12percenttransparency    =0x08000 # the drawing object will be 12.5% transparent 
sim_drawing_emissioncolor            =0x10000 # When used in combination with sim_drawing_itemcolors or sim_drawing_vertexcolors then the specified colors will be for the emissive component 
sim_drawing_facingcamera            =0x20000 # Only for trianglepoints quadpoints discpoints and cubepoints. If specified the normal verctor is calculated to face the camera (each item data requires 3 values less) 
sim_drawing_overlay                    =0x40000 # When specified objects are always drawn on top of "regular objects" 
sim_drawing_itemtransparency        =0x80000  # +1 value per item (each item has its own transparency value (0-1)). Not compatible with sim_drawing_vertexcolors 

# banner values 
# following can be or-combined 
sim_banner_left                        =0x00001 # Banners display on the left of the specified point 
sim_banner_right                    =0x00002 # Banners display on the right of the specified point 
sim_banner_nobackground                =0x00004 # Banners have no background rectangle 
sim_banner_overlay                    =0x00008 # When specified banners are always drawn on top of "regular objects" 
sim_banner_followparentvisibility    =0x00010 # if the object is associated with a scene object then it follows that visibility otherwise it is always visible 
sim_banner_clickselectsparent        =0x00020 # if the object is associated with a scene object then clicking the banner will select the scene object 
sim_banner_clicktriggersevent        =0x00040 # if the banner is clicked an event is triggered (sim_message_eventcallback_bannerclicked and sim_message_bannerclicked are generated) 
sim_banner_facingcamera                =0x00080 # If specified the banner will always face the camera by rotating around the banner's vertical axis (y-axis) 
sim_banner_fullyfacingcamera        =0x00100 # If specified the banner will always fully face the camera (the banner's orientation is same as the camera looking at it) 
sim_banner_backfaceculling            =0x00200 # If specified the banner will only be visible from one side 
sim_banner_keepsamesize                =0x00400 # If specified the banner will always appear in the same size. In that case size represents the character height in pixels 
sim_banner_bitmapfont                =0x00800 # If specified a fixed-size bitmap font is used. The text will also always fully face the camera and be right 
                                             # to the specified position. Bitmap fonts are not clickable 


# particle objects following are mutually exclusive 
sim_particle_points1        =0  # 6 values per point (pt1 and pt2. Pt1 is start position pt2-pt1 is the initial velocity vector). i
                                #Point is 1 pixel big. Only appearance is a point internally handled as a perfect sphere 
sim_particle_points2        =1    # 6 values per point. Point is 2 pixel big. Only appearance is a point internally handled as a perfect sphere 
sim_particle_points4        =2    # 6 values per point. Point is 4 pixel big. Only appearance is a point internally handled as a perfect sphere 
sim_particle_roughspheres    =3    # 6 values per sphere. Only appearance is rough. Internally a perfect sphere 
sim_particle_spheres        =4    # 6 values per sphere. Internally a perfect sphere 




# following can be or-combined 
sim_particle_respondable1to4        =0x0020 # the particles are respondable against shapes (against all objects that have at least one bit 1-4 activated in the global respondable mask) 
sim_particle_respondable5to8        =0x0040 # the particles are respondable against shapes (against all objects that have at least one bit 5-8 activated in the global respondable mask) 
sim_particle_particlerespondable    =0x0080 # the particles are respondable against each other 
sim_particle_ignoresgravity            =0x0100 # the particles ignore the effect of gravity. Not compatible with sim_particle_water 
sim_particle_invisible                =0x0200 # the particles are invisible 
sim_particle_itemsizes                =0x0400 # +1 value per particle (each particle can have a different size) 
sim_particle_itemdensities            =0x0800 # +1 value per particle (each particle can have a different density) 
sim_particle_itemcolors                =0x1000 # +3 values per particle (each particle can have a different color) 
sim_particle_cyclic                    =0x2000 # if the max item count was reached then the first items are overwritten. 
sim_particle_emissioncolor            =0x4000 # When used in combination with sim_particle_itemcolors then the specified colors will be for the emissive component 
sim_particle_water                    =0x8000 # the particles are water particles (no weight in the water (i.e. when z<0)). Not compatible with sim_particle_ignoresgravity 
sim_particle_painttag                =0x10000 # The particles can be seen by vision sensors (sim_particle_invisible must not be set) 




# custom user interface menu attributes 
sim_ui_menu_title        =1
sim_ui_menu_minimize    =2
sim_ui_menu_close        =4
sim_ui_menu_systemblock =8



# Boolean parameters 
sim_boolparam_hierarchy_visible                 =0
sim_boolparam_console_visible                   =1
sim_boolparam_collision_handling_enabled        =2
sim_boolparam_distance_handling_enabled         =3
sim_boolparam_ik_handling_enabled               =4
sim_boolparam_gcs_handling_enabled              =5
sim_boolparam_dynamics_handling_enabled         =6
sim_boolparam_joint_motion_handling_enabled     =7
sim_boolparam_path_motion_handling_enabled      =8
sim_boolparam_proximity_sensor_handling_enabled =9
sim_boolparam_vision_sensor_handling_enabled    =10
sim_boolparam_mill_handling_enabled             =11
sim_boolparam_browser_visible                   =12
sim_boolparam_scene_and_model_load_messages     =13
sim_reserved0                                   =14
sim_boolparam_shape_textures_are_visible        =15
sim_boolparam_display_enabled                   =16
sim_boolparam_infotext_visible                  =17
sim_boolparam_statustext_open                   =18
sim_boolparam_fog_enabled                       =19
sim_boolparam_rml2_available                    =20
sim_boolparam_rml4_available                    =21
sim_boolparam_mirrors_enabled                    =22
sim_boolparam_aux_clip_planes_enabled            =23
sim_boolparam_full_model_copy_from_api            =24
sim_boolparam_realtime_simulation                =25
sim_boolparam_force_show_wireless_emission        =27
sim_boolparam_force_show_wireless_reception        =28
sim_boolparam_video_recording_triggered            =29
sim_boolparam_threaded_rendering_enabled        =32
sim_boolparam_fullscreen                        =33
sim_boolparam_headless                            =34
sim_boolparam_hierarchy_toolbarbutton_enabled    =35
sim_boolparam_browser_toolbarbutton_enabled        =36
sim_boolparam_objectshift_toolbarbutton_enabled    =37
sim_boolparam_objectrotate_toolbarbutton_enabled=38
sim_boolparam_force_calcstruct_all_visible        =39
sim_boolparam_force_calcstruct_all                =40
sim_boolparam_exit_request                        =41
sim_boolparam_play_toolbarbutton_enabled        =42
sim_boolparam_pause_toolbarbutton_enabled        =43
sim_boolparam_stop_toolbarbutton_enabled        =44
sim_boolparam_waiting_for_trigger                =45


# Integer parameters 
sim_intparam_error_report_mode      =0  # Check sim_api_errormessage_... constants above for valid values 
sim_intparam_program_version        =1  # e.g Version 2.1.4 --> 20104. Can only be read 
sim_intparam_instance_count         =2  # do not use anymore (always returns 1 since CoppeliaSim 2.5.11) 
sim_intparam_custom_cmd_start_id    =3  # can only be read 
sim_intparam_compilation_version    =4  # 0=evaluation version 1=full version 2=player version. Can only be read 
sim_intparam_current_page           =5
sim_intparam_flymode_camera_handle  =6  # can only be read 
sim_intparam_dynamic_step_divider   =7  # can only be read 
sim_intparam_dynamic_engine         =8  # 0=Bullet 1=ODE. 2=Vortex.
sim_intparam_server_port_start      =9  # can only be read 
sim_intparam_server_port_range      =10 # can only be read 
sim_intparam_visible_layers         =11
sim_intparam_infotext_style         =12
sim_intparam_settings               =13
sim_intparam_edit_mode_type         =14 # can only be read 
sim_intparam_server_port_next       =15 # is initialized at sim_intparam_server_port_start 
sim_intparam_qt_version             =16 # version of the used Qt framework 
sim_intparam_event_flags_read       =17 # can only be read 
sim_intparam_event_flags_read_clear =18 # can only be read 
sim_intparam_platform               =19 # can only be read 
sim_intparam_scene_unique_id        =20 # can only be read 
sim_intparam_work_thread_count      =21
sim_intparam_mouse_x                =22
sim_intparam_mouse_y                =23
sim_intparam_core_count             =24
sim_intparam_work_thread_calc_time_ms =25
sim_intparam_idle_fps               =26
sim_intparam_prox_sensor_select_down =27
sim_intparam_prox_sensor_select_up  =28
sim_intparam_stop_request_counter   =29
sim_intparam_program_revision       =30
sim_intparam_mouse_buttons          =31
sim_intparam_dynamic_warning_disabled_mask =32
sim_intparam_simulation_warning_disabled_mask =33
sim_intparam_scene_index            =34
sim_intparam_motionplanning_seed    =35
sim_intparam_speedmodifier          =36

# Float parameters 
sim_floatparam_rand=0 # random value (0.0-1.0) 
sim_floatparam_simulation_time_step =1
sim_floatparam_stereo_distance        =2

# String parameters 
sim_stringparam_application_path=0 # path of CoppeliaSim's executable 
sim_stringparam_video_filename=1
sim_stringparam_app_arg1            =2
sim_stringparam_app_arg2            =3
sim_stringparam_app_arg3            =4
sim_stringparam_app_arg4            =5
sim_stringparam_app_arg5            =6
sim_stringparam_app_arg6            =7
sim_stringparam_app_arg7            =8
sim_stringparam_app_arg8            =9
sim_stringparam_app_arg9            =10
sim_stringparam_scene_path_and_name    =13

# Array parameters 
sim_arrayparam_gravity          =0
sim_arrayparam_fog              =1
sim_arrayparam_fog_color        =2
sim_arrayparam_background_color1=3
sim_arrayparam_background_color2=4
sim_arrayparam_ambient_light    =5
sim_arrayparam_random_euler        =6

sim_objintparam_visibility_layer= 10
sim_objfloatparam_abs_x_velocity= 11
sim_objfloatparam_abs_y_velocity= 12
sim_objfloatparam_abs_z_velocity= 13
sim_objfloatparam_abs_rot_velocity= 14
sim_objfloatparam_objbbox_min_x= 15
sim_objfloatparam_objbbox_min_y= 16
sim_objfloatparam_objbbox_min_z= 17
sim_objfloatparam_objbbox_max_x= 18
sim_objfloatparam_objbbox_max_y= 19
sim_objfloatparam_objbbox_max_z= 20
sim_objfloatparam_modelbbox_min_x= 21
sim_objfloatparam_modelbbox_min_y= 22
sim_objfloatparam_modelbbox_min_z= 23
sim_objfloatparam_modelbbox_max_x= 24
sim_objfloatparam_modelbbox_max_y= 25
sim_objfloatparam_modelbbox_max_z= 26
sim_objintparam_collection_self_collision_indicator= 27
sim_objfloatparam_transparency_offset= 28
sim_objintparam_child_role= 29
sim_objintparam_parent_role= 30
sim_objintparam_manipulation_permissions= 31
sim_objintparam_illumination_handle= 32

sim_visionfloatparam_near_clipping= 1000
sim_visionfloatparam_far_clipping= 1001
sim_visionintparam_resolution_x= 1002
sim_visionintparam_resolution_y= 1003
sim_visionfloatparam_perspective_angle= 1004
sim_visionfloatparam_ortho_size= 1005
sim_visionintparam_disabled_light_components= 1006
sim_visionintparam_rendering_attributes= 1007
sim_visionintparam_entity_to_render= 1008
sim_visionintparam_windowed_size_x= 1009
sim_visionintparam_windowed_size_y= 1010
sim_visionintparam_windowed_pos_x= 1011
sim_visionintparam_windowed_pos_y= 1012
sim_visionintparam_pov_focal_blur= 1013
sim_visionfloatparam_pov_blur_distance= 1014
sim_visionfloatparam_pov_aperture= 1015
sim_visionintparam_pov_blur_sampled= 1016
sim_visionintparam_render_mode= 1017

sim_jointintparam_motor_enabled= 2000
sim_jointintparam_ctrl_enabled= 2001
sim_jointfloatparam_pid_p= 2002
sim_jointfloatparam_pid_i= 2003
sim_jointfloatparam_pid_d= 2004
sim_jointfloatparam_intrinsic_x= 2005
sim_jointfloatparam_intrinsic_y= 2006
sim_jointfloatparam_intrinsic_z= 2007
sim_jointfloatparam_intrinsic_qx= 2008
sim_jointfloatparam_intrinsic_qy= 2009
sim_jointfloatparam_intrinsic_qz= 2010
sim_jointfloatparam_intrinsic_qw= 2011
sim_jointfloatparam_velocity= 2012
sim_jointfloatparam_spherical_qx= 2013
sim_jointfloatparam_spherical_qy= 2014
sim_jointfloatparam_spherical_qz= 2015
sim_jointfloatparam_spherical_qw= 2016
sim_jointfloatparam_upper_limit= 2017
sim_jointfloatparam_kc_k= 2018
sim_jointfloatparam_kc_c= 2019
sim_jointfloatparam_ik_weight= 2021
sim_jointfloatparam_error_x= 2022
sim_jointfloatparam_error_y= 2023
sim_jointfloatparam_error_z= 2024
sim_jointfloatparam_error_a= 2025
sim_jointfloatparam_error_b= 2026
sim_jointfloatparam_error_g= 2027
sim_jointfloatparam_error_pos= 2028
sim_jointfloatparam_error_angle= 2029
sim_jointintparam_velocity_lock= 2030
sim_jointintparam_vortex_dep_handle= 2031
sim_jointfloatparam_vortex_dep_multiplication= 2032
sim_jointfloatparam_vortex_dep_offset= 2033

sim_shapefloatparam_init_velocity_x= 3000
sim_shapefloatparam_init_velocity_y= 3001
sim_shapefloatparam_init_velocity_z= 3002
sim_shapeintparam_static= 3003
sim_shapeintparam_respondable= 3004
sim_shapefloatparam_mass= 3005
sim_shapefloatparam_texture_x= 3006
sim_shapefloatparam_texture_y= 3007
sim_shapefloatparam_texture_z= 3008
sim_shapefloatparam_texture_a= 3009
sim_shapefloatparam_texture_b= 3010
sim_shapefloatparam_texture_g= 3011
sim_shapefloatparam_texture_scaling_x= 3012
sim_shapefloatparam_texture_scaling_y= 3013
sim_shapeintparam_culling= 3014
sim_shapeintparam_wireframe= 3015
sim_shapeintparam_compound= 3016
sim_shapeintparam_convex= 3017
sim_shapeintparam_convex_check= 3018
sim_shapeintparam_respondable_mask= 3019
sim_shapefloatparam_init_velocity_a= 3020
sim_shapefloatparam_init_velocity_b= 3021
sim_shapefloatparam_init_velocity_g= 3022
sim_shapestringparam_color_name= 3023
sim_shapeintparam_edge_visibility= 3024
sim_shapefloatparam_shading_angle= 3025
sim_shapefloatparam_edge_angle= 3026
sim_shapeintparam_edge_borders_hidden= 3027

sim_proxintparam_ray_invisibility= 4000

sim_forcefloatparam_error_x= 5000
sim_forcefloatparam_error_y= 5001
sim_forcefloatparam_error_z= 5002
sim_forcefloatparam_error_a= 5003
sim_forcefloatparam_error_b= 5004
sim_forcefloatparam_error_g= 5005
sim_forcefloatparam_error_pos= 5006
sim_forcefloatparam_error_angle= 5007

sim_lightintparam_pov_casts_shadows= 8000

sim_cameraintparam_disabled_light_components= 9000
sim_camerafloatparam_perspective_angle= 9001
sim_camerafloatparam_ortho_size= 9002
sim_cameraintparam_rendering_attributes= 9003
sim_cameraintparam_pov_focal_blur= 9004
sim_camerafloatparam_pov_blur_distance= 9005
sim_camerafloatparam_pov_aperture= 9006
sim_cameraintparam_pov_blur_samples= 9007

sim_dummyintparam_link_type= 10000

sim_mirrorfloatparam_width= 12000
sim_mirrorfloatparam_height= 12001
sim_mirrorfloatparam_reflectance= 12002
sim_mirrorintparam_enable= 12003

sim_pplanfloatparam_x_min= 20000
sim_pplanfloatparam_x_range= 20001
sim_pplanfloatparam_y_min= 20002
sim_pplanfloatparam_y_range= 20003
sim_pplanfloatparam_z_min= 20004
sim_pplanfloatparam_z_range= 20005
sim_pplanfloatparam_delta_min= 20006
sim_pplanfloatparam_delta_range= 20007

sim_mplanintparam_nodes_computed= 25000
sim_mplanintparam_prepare_nodes= 25001
sim_mplanintparam_clear_nodes= 25002

# User interface elements 
sim_gui_menubar                        =0x0001
sim_gui_popups                        =0x0002
sim_gui_toolbar1                    =0x0004
sim_gui_toolbar2                    =0x0008
sim_gui_hierarchy                    =0x0010
sim_gui_infobar                        =0x0020
sim_gui_statusbar                    =0x0040
sim_gui_scripteditor                =0x0080
sim_gui_scriptsimulationparameters    =0x0100
sim_gui_dialogs                        =0x0200
sim_gui_browser                        =0x0400
sim_gui_all                            =0xffff


# Joint modes 
sim_jointmode_passive       =0
sim_jointmode_motion        =1
sim_jointmode_ik            =2
sim_jointmode_ikdependent   =3
sim_jointmode_dependent     =4
sim_jointmode_force         =5


# Navigation and selection modes with the mouse. Lower byte values are mutually exclusive upper byte bits can be combined 
sim_navigation_passive                    =0x0000
sim_navigation_camerashift                =0x0001
sim_navigation_camerarotate                =0x0002
sim_navigation_camerazoom                =0x0003
sim_navigation_cameratilt                =0x0004
sim_navigation_cameraangle                =0x0005
sim_navigation_camerafly                =0x0006
sim_navigation_objectshift                =0x0007
sim_navigation_objectrotate                =0x0008
sim_navigation_reserved2                =0x0009
sim_navigation_reserved3                =0x000A
sim_navigation_jointpathtest            =0x000B
sim_navigation_ikmanip                    =0x000C
sim_navigation_objectmultipleselection    =0x000D
# Bit-combine following values and add them to one of above's values for a valid navigation mode 
sim_navigation_reserved4                =0x0100
sim_navigation_clickselection            =0x0200
sim_navigation_ctrlselection            =0x0400
sim_navigation_shiftselection            =0x0800
sim_navigation_camerazoomwheel            =0x1000
sim_navigation_camerarotaterightbutton    =0x2000



#Remote API constants
SIMX_VERSION                    =0 
# Remote API message header structure 
SIMX_HEADER_SIZE                =18
simx_headeroffset_crc           =0    # 1 simxUShort. Generated by the client or server. The CRC for the message 
simx_headeroffset_version       =2    # 1 byte. Generated by the client or server. The version of the remote API software 
simx_headeroffset_message_id    =3    # 1 simxInt. Generated by the client (and used in a reply by the server) 
simx_headeroffset_client_time   =7    # 1 simxInt. Client time stamp generated by the client (and sent back by the server) 
simx_headeroffset_server_time   =11    # 1 simxInt. Generated by the server when a reply is generated. The server timestamp 
simx_headeroffset_scene_id      =15    # 1 simxUShort. Generated by the server. A unique ID identifying the scene currently displayed 
simx_headeroffset_server_state  =17    # 1 byte. Generated by the server. Bit coded 0 set --> simulation not stopped 1 set --> simulation paused 2 set --> real-time switch on 3-5 edit mode type (0=no edit mode 1=triangle 2=vertex 3=edge 4=path 5=UI)  

# Remote API command header 
SIMX_SUBHEADER_SIZE                 =26
simx_cmdheaderoffset_mem_size       =0    # 1 simxInt. Generated by the client or server. The buffer size of the command. 
simx_cmdheaderoffset_full_mem_size  =4    # 1 simxInt. Generated by the client or server. The full buffer size of the command (applies to split chunks). 
simx_cmdheaderoffset_pdata_offset0  =8    # 1 simxUShort. Generated by the client or server. The amount of data that is part of the command identification. 
simx_cmdheaderoffset_pdata_offset1  =10    # 1 simxInt. Generated by the client or server. The amount of shift of the pure data buffer (applies to split chunks). 
simx_cmdheaderoffset_cmd=14    # 1 simxInt. Generated by the client (and used in a reply by the server). The command combined with the operation mode of the command. 
simx_cmdheaderoffset_delay_or_split =18    # 1 simxUShort. Generated by the client or server. The amount of delay in ms of a continuous command or the max. pure data size to send at once (applies to split commands). 
simx_cmdheaderoffset_sim_time       =20    # 1 simxInt. Generated by the server. The simulation time (in ms) when the command was executed (or 0 if simulation is not running) 
simx_cmdheaderoffset_status         =24    # 1 byte. Generated by the server. (1 bit 0 is set --> error in function execution on server side). The client writes bit 1 if command cannot be overwritten
simx_cmdheaderoffset_reserved       =25    # 1 byte. Not yet used 





# Regular operation modes 
simx_opmode_oneshot                =0x000000 # sends command as one chunk. Reply will also come as one chunk. Doesn't wait for the reply. 
simx_opmode_blocking            =0x010000 # sends command as one chunk. Reply will also come as one chunk. Waits for the reply (_REPLY_WAIT_TIMEOUT_IN_MS is the timeout). 
simx_opmode_oneshot_wait        =0x010000 # sends command as one chunk. Reply will also come as one chunk. Waits for the reply (_REPLY_WAIT_TIMEOUT_IN_MS is the timeout). 
simx_opmode_continuous            =0x020000  
simx_opmode_streaming            =0x020000 # sends command as one chunk. Command will be stored on the server and always executed 
                                                      #(every x ms (as far as possible) where x can be 0-65535. just add x to opmode_continuous). 
                                                      # A reply will be sent continuously each time as one chunk. Doesn't wait for the reply. 

# Operation modes for heavy data 
simx_opmode_oneshot_split        =0x030000   # sends command as several chunks (max chunk size is x bytes where x can be _MIN_SPLIT_AMOUNT_IN_BYTES-65535. Just add x to opmode_oneshot_split). Reply will also come as several chunks. Doesn't wait for the reply.      
simx_opmode_continuous_split    =0x040000
simx_opmode_streaming_split    =0x040000    # sends command as several chunks (max chunk size is x bytes where x can be _MIN_SPLIT_AMOUNT_IN_BYTES-65535. Just add x to opmode_continuous_split). Command will be stored on the server and always executed. A reply will be sent continuously each time as several chunks. Doesn't wait for the reply. 

# Special operation modes 
simx_opmode_discontinue            =0x050000    # removes and cancels all commands stored on the client or server side (also continuous commands) 
simx_opmode_buffer                =0x060000    # doesn't send anything but checks if a reply for the given command is available in the input buffer (i.e. previously received from the server) 
simx_opmode_remove                =0x070000    # doesn't send anything and doesn't return any specific value. It just erases a similar command reply in the inbox (to free some memory) 


# Command return codes 
simx_return_ok                    =0x000000
simx_return_novalue_flag        =0x000001        # input buffer doesn't contain the specified command 
simx_return_timeout_flag        =0x000002        # command reply not received in time for opmode_oneshot_wait operation mode 
simx_return_illegal_opmode_flag    =0x000004        # command doesn't support the specified operation mode 
simx_return_remote_error_flag    =0x000008        # command caused an error on the server side 
simx_return_split_progress_flag    =0x000010        # previous similar command not yet fully processed (applies to opmode_oneshot_split operation modes) 
simx_return_local_error_flag    =0x000020        # command caused an error on the client side 
simx_return_initialize_error_flag    =0x000040        # simxStart was not yet called 

# Following for backward compatibility (same as above) 
simx_error_noerror                =0x000000
simx_error_novalue_flag            =0x000001        # input buffer doesn't contain the specified command 
simx_error_timeout_flag            =0x000002        # command reply not received in time for opmode_oneshot_wait operation mode 
simx_error_illegal_opmode_flag    =0x000004        # command doesn't support the specified operation mode 
simx_error_remote_error_flag    =0x000008        # command caused an error on the server side 
simx_error_split_progress_flag    =0x000010        # previous similar command not yet fully processed (applies to opmode_oneshot_split operation modes) 
simx_error_local_error_flag        =0x000020        # command caused an error on the client side 
simx_error_initialize_error_flag        =0x000040        # simxStart was not yet called 


sim_announce_containsnonpurenonconvexshapes = 2
sim_announce_containsstaticshapesondynamicconstruction = 3
sim_announce_newtondynamicrandommeshnotsupported = 6
sim_announce_pureconenotsupported = 0
sim_announce_purehollowshapenotsupported = 4
sim_announce_purespheroidnotsupported = 1
sim_announce_vortexpluginisdemo = 5
sim_api_error_output = 2
sim_api_error_report = 1
sim_api_warning_output = 4
sim_appobj_motionplanning_type = 121
sim_autoquit = 262144
sim_autostart = 131072
sim_boolparam_calcmodules_toolbarbutton_enabled = 47
sim_boolparam_joint_motion_handling_enabled_deprecated = 7
sim_boolparam_objproperties_toolbarbutton_enabled = 46
sim_boolparam_online_mode = 49
sim_boolparam_path_motion_handling_enabled_deprecated = 8
sim_boolparam_reserved1 = 30
sim_boolparam_reserved2 = 31
sim_boolparam_reserved3 = 24
sim_boolparam_rosinterface_donotrunmainscript = 48
sim_boolparam_scene_closing = 52
sim_boolparam_show_w_emitters = 53
sim_boolparam_show_w_receivers = 54
sim_boolparam_use_glfinish_cmd = 26
sim_boolparam_xr_jobfunc = 55
sim_boolparam_xr_palletrepository = 51
sim_boolparam_xr_partrepository = 50
sim_buffer_base64 = 12
sim_buffer_clamp = 256
sim_buffer_double = 7
sim_buffer_float = 6
sim_buffer_int16 = 3
sim_buffer_int32 = 5
sim_buffer_int8 = 1
sim_buffer_split = 13
sim_buffer_uint16 = 2
sim_buffer_uint32 = 4
sim_buffer_uint8 = 0
sim_buffer_uint8argb = 11
sim_buffer_uint8bgr = 9
sim_buffer_uint8rgb = 8
sim_buffer_uint8rgba = 10
sim_bullet_body_angulardamping = 6005
sim_bullet_body_autoshrinkconvex = 8004
sim_bullet_body_bitcoded = 7001
sim_bullet_body_bool_end = 8005
sim_bullet_body_bool_start = 8000
sim_bullet_body_float_end = 6008
sim_bullet_body_float_start = 6000
sim_bullet_body_friction = 6003
sim_bullet_body_int_end = 7002
sim_bullet_body_int_start = 7000
sim_bullet_body_lineardamping = 6004
sim_bullet_body_nondefaultcollisionmargingfactor = 6006
sim_bullet_body_nondefaultcollisionmargingfactorconvex = 6007
sim_bullet_body_oldfriction = 6002
sim_bullet_body_restitution = 6001
sim_bullet_body_sticky = 8001
sim_bullet_body_usenondefaultcollisionmargin = 8002
sim_bullet_body_usenondefaultcollisionmarginconvex = 8003
sim_bullet_constraintsolvertype_dantzig = 2
sim_bullet_constraintsolvertype_nncg = 1
sim_bullet_constraintsolvertype_projectedgaussseidel = 3
sim_bullet_constraintsolvertype_sequentialimpulse = 0
sim_bullet_global_bitcoded = 1002
sim_bullet_global_bool_end = 2002
sim_bullet_global_bool_start = 2000
sim_bullet_global_collisionmarginfactor = 3
sim_bullet_global_constraintsolvertype = 1003
sim_bullet_global_constraintsolvingiterations = 1001
sim_bullet_global_float_end = 4
sim_bullet_global_float_start = 0
sim_bullet_global_fullinternalscaling = 2001
sim_bullet_global_int_end = 1004
sim_bullet_global_int_start = 1000
sim_bullet_global_internalscalingfactor = 2
sim_bullet_global_stepsize = 1
sim_bullet_joint_bool_end = 5001
sim_bullet_joint_bool_start = 5000
sim_bullet_joint_float_end = 3004
sim_bullet_joint_float_start = 3000
sim_bullet_joint_int_end = 4001
sim_bullet_joint_int_start = 4000
sim_bullet_joint_normalcfm = 3003
sim_bullet_joint_stopcfm = 3002
sim_bullet_joint_stoperp = 3001
sim_callbackid_dynstep = 2
sim_callbackid_rossubscriber = 1
sim_callbackid_userdefined = 1000
sim_childscriptattribute_automaticcascadingcalls = 3
sim_childscriptattribute_enabled = 4
sim_colorcomponent_ambient = 0
sim_colorcomponent_ambient_diffuse = 0
sim_colorcomponent_auxiliary = 5
sim_colorcomponent_diffuse = 1
sim_colorcomponent_emission = 3
sim_colorcomponent_specular = 2
sim_colorcomponent_transparency = 4
sim_customizationscriptattribute_activeduringsimulation = 0
sim_customizationscriptattribute_cleanupbeforesave = 5
sim_displayattribute_FREE = 4194304
sim_displayattribute_colorcoded = 8192
sim_displayattribute_colorcodedpickpass = 4096
sim_displayattribute_colorcodedtriangles = 134217728
sim_displayattribute_depthpass = 2
sim_displayattribute_dynamiccontentonly = 131072
sim_displayattribute_forbidedges = 256
sim_displayattribute_forbidwireframe = 128
sim_displayattribute_forcewireframe = 64
sim_displayattribute_forvisionsensor = 2048
sim_displayattribute_groupselection = 16
sim_displayattribute_ignorelayer = 1024
sim_displayattribute_ignorerenderableflag = 1048576
sim_displayattribute_inertiaonly = 32768
sim_displayattribute_mainselection = 32
sim_displayattribute_mirror = 262144
sim_displayattribute_nodrawingobjects = 33554432
sim_displayattribute_noghosts = 8388608
sim_displayattribute_noopenglcallbacks = 2097152
sim_displayattribute_noparticles = 67108864
sim_displayattribute_nopointclouds = 16777216
sim_displayattribute_originalcolors = 512
sim_displayattribute_pickpass = 4
sim_displayattribute_renderpass = 1
sim_displayattribute_selected = 8
sim_displayattribute_thickEdges = 65536
sim_displayattribute_trianglewireframe = 16384
sim_displayattribute_useauxcomponent = 524288
sim_drawing_auxchannelcolor1 = 2097152
sim_drawing_auxchannelcolor2 = 4194304
sim_drawing_persistent = 1048576
sim_dummy_linktype_dynamics_force_constraint = 1
sim_dummy_linktype_dynamics_loop_closure = 0
sim_dummy_linktype_gcs_loop_closure = 2
sim_dummy_linktype_gcs_target = 4
sim_dummy_linktype_gcs_tip = 3
sim_dummy_linktype_ik_tip_target = 5
sim_dummy_linktype_reserved = 6
sim_dummyfloatparam_follow_path_offset = 10002
sim_dummyintparam_follow_path = 10001
sim_dynamicsimicon_none = 0
sim_dynamicsimicon_objectisdynamicallysimulated = 1
sim_dynamicsimicon_objectisnotdynamicallyenabled = 2
sim_dynmat_default = 2310013
sim_dynmat_floor = 2310021
sim_dynmat_foot = 2310018
sim_dynmat_gripper = 2310020
sim_dynmat_highfriction = 2310014
sim_dynmat_lowfriction = 2310015
sim_dynmat_nofriction = 2310016
sim_dynmat_reststackgrasp = 2310017
sim_dynmat_wheel = 2310019
sim_filedlg_type_folder = 3
sim_filedlg_type_load = 0
sim_filedlg_type_load_multiple = 2
sim_filedlg_type_save = 1
sim_filtercomponent_3x3filter_deprecated = 18
sim_filtercomponent_5x5filter_deprecated = 19
sim_filtercomponent_addbuffer1_deprecated = 10
sim_filtercomponent_addtobuffer1_deprecated = 30
sim_filtercomponent_binary_deprecated = 28
sim_filtercomponent_blobextraction_deprecated = 34
sim_filtercomponent_circularcut_deprecated = 23
sim_filtercomponent_colorsegmentation_deprecated = 33
sim_filtercomponent_correlationwithbuffer1_deprecated = 32
sim_filtercomponent_customized_deprecated = 1000
sim_filtercomponent_edge_deprecated = 21
sim_filtercomponent_frombuffer1_deprecated = 7
sim_filtercomponent_frombuffer2_deprecated = 8
sim_filtercomponent_horizontalflip_deprecated = 13
sim_filtercomponent_imagetocoord_deprecated = 35
sim_filtercomponent_intensityscale_deprecated = 25
sim_filtercomponent_keeporremovecolors_deprecated = 26
sim_filtercomponent_multiplywithbuffer1_deprecated = 12
sim_filtercomponent_normalize_deprecated = 24
sim_filtercomponent_originaldepth_deprecated = 2
sim_filtercomponent_originalimage_deprecated = 1
sim_filtercomponent_pixelchange_deprecated = 36
sim_filtercomponent_rectangularcut_deprecated = 22
sim_filtercomponent_resize_deprecated = 17
sim_filtercomponent_rotate_deprecated = 15
sim_filtercomponent_scaleandoffsetcolors_deprecated = 27
sim_filtercomponent_sharpen_deprecated = 20
sim_filtercomponent_shift_deprecated = 16
sim_filtercomponent_subtractbuffer1_deprecated = 11
sim_filtercomponent_subtractfrombuffer1_deprecated = 31
sim_filtercomponent_swapbuffers_deprecated = 9
sim_filtercomponent_swapwithbuffer1_deprecated = 29
sim_filtercomponent_tobuffer1_deprecated = 5
sim_filtercomponent_tobuffer2_deprecated = 6
sim_filtercomponent_todepthoutput_deprecated = 38
sim_filtercomponent_tooutput_deprecated = 4
sim_filtercomponent_uniformimage_deprecated = 3
sim_filtercomponent_velodyne_deprecated = 37
sim_filtercomponent_verticalflip_deprecated = 14
sim_floatparam_dynamic_step_size = 3
sim_floatparam_mouse_wheel_zoom_factor = 4
sim_gui_headless = 65536
sim_handle_app = -13
sim_handle_scene = -12
sim_handleflag_altname = 4194304
sim_handleflag_axis = 4194304
sim_handleflag_camera = 4194304
sim_handleflag_codedstring = 4194304
sim_handleflag_depthbuffer = 8388608
sim_handleflag_depthbuffermeters = 8388608
sim_handleflag_extended = 4194304
sim_handleflag_greyscale = 4194304
sim_handleflag_keeporiginal = 4194304
sim_handleflag_rawvalue = 16777216
sim_handleflag_resetforce = 4194304
sim_handleflag_resetforcetorque = 12582912
sim_handleflag_resettorque = 8388608
sim_handleflag_silenterror = 33554432
sim_handleflag_togglevisibility = 4194304
sim_holonomicpathplanning_abg = 4
sim_holonomicpathplanning_xabg = 6
sim_holonomicpathplanning_xg = 1
sim_holonomicpathplanning_xy = 0
sim_holonomicpathplanning_xyabg = 7
sim_holonomicpathplanning_xyg = 3
sim_holonomicpathplanning_xyz = 2
sim_holonomicpathplanning_xyzabg = 8
sim_holonomicpathplanning_xyzg = 5
sim_imgcomb_horizontal = 1
sim_imgcomb_vertical = 0
sim_intparam_dynamic_iteration_count = 37
sim_intparam_job_count = 38
sim_intparam_program_full_version = 39
sim_jointmode_motion_deprecated = 1
sim_jointmode_reserved_previously_ikdependent = 3
sim_lightfloatparam_const_attenuation = 8003
sim_lightfloatparam_lin_attenuation = 8004
sim_lightfloatparam_quad_attenuation = 8005
sim_lightfloatparam_spot_cutoff = 8002
sim_lightfloatparam_spot_exponent = 8001
sim_lock_nonui_wants_to_write = 2
sim_lock_ui_wants_to_read = 0
sim_lock_ui_wants_to_write = 1
sim_lua_arg_charbuff = 6
sim_lua_arg_double = 7
sim_message_eventcallback_beforerendering = 316
sim_message_eventcallback_colladaplugin = 304
sim_message_eventcallback_extrenderer_light = 318
sim_message_eventcallback_extrenderer_mesh = 319
sim_message_eventcallback_extrenderer_start = 317
sim_message_eventcallback_extrenderer_stop = 320
sim_message_eventcallback_extrenderer_triangles = 333
sim_message_eventcallback_instanceabouttoswitch = 335
sim_message_eventcallback_lastinstancepass = 336
sim_message_eventcallback_opengl = 305
sim_message_eventcallback_openglcameraview = 307
sim_message_eventcallback_openglframe = 306
sim_message_eventcallback_pathplanningplugin = 303
sim_message_eventcallback_pickselectdown = 310
sim_message_eventcallback_proxsensorselectdown = 308
sim_message_eventcallback_proxsensorselectup = 309
sim_message_eventcallback_reserved10 = 325
sim_message_eventcallback_reserved11 = 326
sim_message_eventcallback_reserved12 = 327
sim_message_eventcallback_reserved13 = 328
sim_message_eventcallback_reserved14 = 329
sim_message_eventcallback_reserved15 = 330
sim_message_eventcallback_reserved16 = 331
sim_message_eventcallback_reserved17 = 332
sim_message_eventcallback_reserved18 = 301
sim_message_eventcallback_reserved19 = 302
sim_message_eventcallback_reserved6 = 321
sim_message_eventcallback_reserved7 = 322
sim_message_eventcallback_reserved8 = 323
sim_message_eventcallback_reserved9 = 324
sim_message_eventcallback_rmlinfo = 315
sim_message_eventcallback_rmlpos = 311
sim_message_eventcallback_rmlremove = 314
sim_message_eventcallback_rmlstep = 313
sim_message_eventcallback_rmlvel = 312
sim_message_eventcallback_simulationabouttoend = 334
sim_message_eventcallback_uipass = 337
sim_message_pick_select_down = 11
sim_message_prox_sensor_select_down = 9
sim_message_prox_sensor_select_up = 10
sim_message_scene_loaded = 8
sim_millintparam_volume_type = 11000
sim_modelproperty_not_showasinsidemodel = 1024
sim_modelproperty_scripts_inactive = 512
sim_msgbox_buttons_ok = 0
sim_msgbox_buttons_okcancel = 3
sim_msgbox_buttons_yesno = 1
sim_msgbox_buttons_yesnocancel = 2
sim_msgbox_return_cancel = 0
sim_msgbox_return_error = 4
sim_msgbox_return_no = 1
sim_msgbox_return_ok = 3
sim_msgbox_return_yes = 2
sim_msgbox_type_critical = 3
sim_msgbox_type_info = 0
sim_msgbox_type_question = 1
sim_msgbox_type_warning = 2
sim_navigation_camerarotatemiddlebutton = 8192
sim_navigation_createpathpoint = 256
sim_navigation_reserved5 = 12
sim_navigation_reserved6 = 13
sim_newton_body_angulardrag = 33005
sim_newton_body_bitcoded = 34001
sim_newton_body_bool_end = 35002
sim_newton_body_bool_start = 35000
sim_newton_body_fastmoving = 35001
sim_newton_body_float_end = 33006
sim_newton_body_float_start = 33000
sim_newton_body_int_end = 34002
sim_newton_body_int_start = 34000
sim_newton_body_kineticfriction = 33002
sim_newton_body_lineardrag = 33004
sim_newton_body_restitution = 33003
sim_newton_body_staticfriction = 33001
sim_newton_global_bitcoded = 28002
sim_newton_global_bool_end = 29004
sim_newton_global_bool_start = 29000
sim_newton_global_constraintsolvingiterations = 28001
sim_newton_global_contactmergetolerance = 27002
sim_newton_global_exactsolver = 29002
sim_newton_global_float_end = 27003
sim_newton_global_float_start = 27000
sim_newton_global_highjointaccuracy = 29003
sim_newton_global_int_end = 28003
sim_newton_global_int_start = 28000
sim_newton_global_multithreading = 29001
sim_newton_global_stepsize = 27001
sim_newton_joint_bool_end = 32001
sim_newton_joint_bool_start = 32000
sim_newton_joint_dependencyfactor = 30001
sim_newton_joint_dependencyoffset = 30002
sim_newton_joint_dependentobjectid = 31002
sim_newton_joint_float_end = 30003
sim_newton_joint_float_start = 30000
sim_newton_joint_int_end = 31003
sim_newton_joint_int_start = 31000
sim_newton_joint_objectid = 31001
sim_objdynprop_dynamic = 1
sim_objdynprop_respondable = 2
sim_object_octree_type = 15
sim_object_pointcloud_type = 16
sim_object_reserved3 = 10
sim_object_type_end = 108
sim_objectproperty_cannotdelete = 8192
sim_objectproperty_cannotdeleteduringsim = 16384
sim_objfloatparam_size_factor = 34
sim_objparam_end = 999
sim_objstringparam_dna = 33
sim_objstringparam_unique_id = 35
sim_ode_body_angulardamping = 15005
sim_ode_body_bool_end = 17001
sim_ode_body_bool_start = 17000
sim_ode_body_float_end = 15006
sim_ode_body_float_start = 15000
sim_ode_body_friction = 15001
sim_ode_body_int_end = 16002
sim_ode_body_int_start = 16000
sim_ode_body_lineardamping = 15004
sim_ode_body_maxcontacts = 16001
sim_ode_body_softcfm = 15003
sim_ode_body_softerp = 15002
sim_ode_global_bitcoded = 10002
sim_ode_global_bool_end = 11003
sim_ode_global_bool_start = 11000
sim_ode_global_cfm = 9003
sim_ode_global_constraintsolvingiterations = 10001
sim_ode_global_erp = 9004
sim_ode_global_float_end = 9005
sim_ode_global_float_start = 9000
sim_ode_global_fullinternalscaling = 11001
sim_ode_global_int_end = 10004
sim_ode_global_int_start = 10000
sim_ode_global_internalscalingfactor = 9002
sim_ode_global_quickstep = 11002
sim_ode_global_randomseed = 10003
sim_ode_global_stepsize = 9001
sim_ode_joint_bool_end = 14001
sim_ode_joint_bool_start = 14000
sim_ode_joint_bounce = 12003
sim_ode_joint_float_end = 12006
sim_ode_joint_float_start = 12000
sim_ode_joint_fudgefactor = 12004
sim_ode_joint_int_end = 13001
sim_ode_joint_int_start = 13000
sim_ode_joint_normalcfm = 12005
sim_ode_joint_stopcfm = 12002
sim_ode_joint_stoperp = 12001
sim_pathplanning_holonomic = 0
sim_pathplanning_nonholonomic = 2
sim_pathplanning_reserved = 1
sim_pathproperty_auto_velocity_profile_rotation_deprecated = 512
sim_pathproperty_auto_velocity_profile_translation_deprecated = 256
sim_pathproperty_endpoints_at_zero_deprecated = 1024
sim_pathproperty_infinite_acceleration_deprecated = 32
sim_pathproperty_invert_velocity_deprecated = 16
sim_physics_bullet = 0
sim_physics_newton = 3
sim_physics_ode = 1
sim_physics_vortex = 2
sim_pov_aluminum = 60
sim_pov_beer_bottle = 33
sim_pov_blood_marble = 2
sim_pov_blue_agate = 3
sim_pov_blue_glass = 35
sim_pov_bold_glass = 31
sim_pov_brass_metal = 40
sim_pov_brass_valley = 53
sim_pov_bright_bronze = 61
sim_pov_bronze_metal = 42
sim_pov_brown_agate = 5
sim_pov_brushed_aluminum = 49
sim_pov_cherry_wood = 8
sim_pov_chrome_metal = 39
sim_pov_copper_metal = 41
sim_pov_cork = 63
sim_pov_dark_wood = 10
sim_pov_dmf_dark_oak = 21
sim_pov_dmf_light_oak = 20
sim_pov_dmf_wood1 = 14
sim_pov_dmf_wood2 = 15
sim_pov_dmf_wood3 = 16
sim_pov_dmf_wood4 = 17
sim_pov_dmf_wood5 = 18
sim_pov_dmf_wood6 = 19
sim_pov_emb_wood1 = 22
sim_pov_glass = 26
sim_pov_glass2 = 27
sim_pov_glass3 = 28
sim_pov_gold_metal = 44
sim_pov_gold_nugget = 59
sim_pov_green_glass = 29
sim_pov_light_glass = 30
sim_pov_lightning = 64
sim_pov_mirror = 65
sim_pov_new_brass = 47
sim_pov_new_penny = 57
sim_pov_orange_glass = 37
sim_pov_pattern_null = 0
sim_pov_pine_wood = 9
sim_pov_pink_alabaster = 7
sim_pov_pink_granite = 6
sim_pov_polished_brass = 46
sim_pov_polished_chrome = 45
sim_pov_rose_wood = 24
sim_pov_ruby_glass = 34
sim_pov_rust = 54
sim_pov_rusty_iron = 55
sim_pov_sandal_wood = 25
sim_pov_sapphire_agate = 4
sim_pov_silver1 = 50
sim_pov_silver2 = 51
sim_pov_silver3 = 52
sim_pov_silver_metal = 43
sim_pov_soft_silver = 56
sim_pov_spun_brass = 48
sim_pov_tan_wood = 11
sim_pov_tinny_brass = 58
sim_pov_tom_wood = 13
sim_pov_vicks_bottle_glass = 38
sim_pov_water = 62
sim_pov_white_marble = 1
sim_pov_white_wood = 12
sim_pov_wine_bottle = 32
sim_pov_yellow_glass = 36
sim_pov_yellow_pine = 23
sim_proxintparam_entity_to_detect = 4002
sim_proxintparam_volume_type = 4001
sim_pure_primitive_cone = 6
sim_pure_primitive_cuboid = 3
sim_pure_primitive_cylinder = 5
sim_pure_primitive_disc = 2
sim_pure_primitive_heightfield = 7
sim_pure_primitive_none = 0
sim_pure_primitive_plane = 1
sim_pure_primitive_spheroid = 4
sim_rendermode_auxchannels = 1
sim_rendermode_colorcoded = 2
sim_rendermode_extrenderer = 5
sim_rendermode_extrendererwindowed = 6
sim_rendermode_opengl = 0
sim_rendermode_opengl3 = 7
sim_rendermode_opengl3windowed = 8
sim_rendermode_povray = 3
sim_rendermode_reserved = 4
sim_script_arg_bool = 1
sim_script_arg_charbuff = 6
sim_script_arg_double = 7
sim_script_arg_float = 3
sim_script_arg_int32 = 2
sim_script_arg_invalid = 5
sim_script_arg_null = 0
sim_script_arg_string = 4
sim_script_arg_table = 8
sim_scriptattribute_debuglevel = 6
sim_scriptattribute_enabled = 4
sim_scriptattribute_executioncount = 2
sim_scriptattribute_executionorder = 1
sim_scriptattribute_scripttype = 7
sim_scriptdebug_allcalls = 3
sim_scriptdebug_callsandvars = 5
sim_scriptdebug_none = 0
sim_scriptdebug_syscalls = 1
sim_scriptdebug_vars = 4
sim_scriptdebug_vars_interval = 2
sim_scriptexecorder_first = 0
sim_scriptexecorder_last = 2
sim_scriptexecorder_normal = 1
sim_scriptthreadresume_actuation_first = 1
sim_scriptthreadresume_actuation_last = 2
sim_scriptthreadresume_allnotyetresumed = -1
sim_scriptthreadresume_custom = 5
sim_scriptthreadresume_default = 0
sim_scriptthreadresume_launch = -2
sim_scriptthreadresume_sensing_first = 3
sim_scriptthreadresume_sensing_last = 4
sim_scripttreetraversal_forward = 1
sim_scripttreetraversal_parent = 2
sim_scripttreetraversal_reverse = 0
sim_scripttype_addonfunction = 3
sim_scripttype_addonscript = 2
sim_scripttype_contactcallback_old = 5
sim_scripttype_generalcallback_old = 7
sim_scripttype_jointctrlcallback_old = 4
sim_scripttype_sandboxscript = 8
sim_scripttype_threaded = 240
sim_shapefloatparam_init_ang_velocity_x = 3020
sim_shapefloatparam_init_ang_velocity_y = 3021
sim_shapefloatparam_init_ang_velocity_z = 3022
sim_stack_table_circular_ref = -4
sim_stack_table_empty = 0
sim_stack_table_map = -2
sim_stack_table_not_table = -3
sim_stringparam_additional_addonscript = 12
sim_stringparam_additional_addonscript_firstscene = 11
sim_stringparam_job = 17
sim_stringparam_job0 = 18
sim_stringparam_job99 = 117
sim_stringparam_machine_id = 119
sim_stringparam_machine_id_legacy = 120
sim_stringparam_remoteapi_temp_file_dir = 16
sim_stringparam_scene_name = 15
sim_stringparam_scene_path = 14
sim_stringparam_scene_unique_id = 118
sim_syscb_actuation = 5
sim_syscb_aftercopy = 13
sim_syscb_aftercreate = 25
sim_syscb_afterdelete = 24
sim_syscb_afterinstanceswitch = 11
sim_syscb_aftersimulation = 4
sim_syscb_aos_resume = 16
sim_syscb_aos_run = 14
sim_syscb_aos_suspend = 15
sim_syscb_beforecopy = 12
sim_syscb_beforedelete = 23
sim_syscb_beforeinstanceswitch = 10
sim_syscb_beforemainscript = 28
sim_syscb_beforesimulation = 3
sim_syscb_br = 200
sim_syscb_cleanup = 1
sim_syscb_contactcallback = 18
sim_syscb_customcallback1 = 19
sim_syscb_customcallback2 = 20
sim_syscb_customcallback3 = 21
sim_syscb_customcallback4 = 22
sim_syscb_dyncallback = 27
sim_syscb_init = 0
sim_syscb_jointcallback = 17
sim_syscb_nonsimulation = 2
sim_syscb_resume = 9
sim_syscb_sensing = 6
sim_syscb_suspend = 8
sim_syscb_suspended = 7
sim_syscb_threadmain = 26
sim_syscb_trigger = 30
sim_syscb_userconfig = 31
sim_syscb_vision = 29
sim_syscb_xr = 200
sim_texturemap_cube = 3
sim_texturemap_cylinder = 1
sim_texturemap_plane = 0
sim_texturemap_sphere = 2
sim_ui_property_pauseactive = 4096
sim_ui_property_systemblockcanmovetofront = 2048
sim_uint64param_simulation_time_ns = 1
sim_uint64param_simulation_time_step_ns = 0
sim_visionintparam_perspective_operation = 1018
sim_volume_cone = 3
sim_volume_cylinder = 1
sim_volume_disc = 2
sim_volume_pyramid = 0
sim_volume_randomizedray = 5
sim_volume_ray = 4
sim_vortex_body_adhesiveforce = 24015
sim_vortex_body_angularvelocitydamping = 24017
sim_vortex_body_autoangulardamping = 26009
sim_vortex_body_autoangulardampingtensionratio = 24033
sim_vortex_body_autosleepangularaccelthreshold = 24031
sim_vortex_body_autosleepangularspeedthreshold = 24030
sim_vortex_body_autosleeplinearaccelthreshold = 24029
sim_vortex_body_autosleeplinearspeedthreshold = 24028
sim_vortex_body_autosleepsteplivethreshold = 25007
sim_vortex_body_autoslip = 26005
sim_vortex_body_bitcoded = 25006
sim_vortex_body_bool_end = 26010
sim_vortex_body_bool_start = 26000
sim_vortex_body_compliance = 24011
sim_vortex_body_convexshapesasrandom = 26002
sim_vortex_body_damping = 24012
sim_vortex_body_fastmoving = 26004
sim_vortex_body_float_end = 24037
sim_vortex_body_float_start = 24000
sim_vortex_body_int_end = 25009
sim_vortex_body_int_start = 25000
sim_vortex_body_linearvelocitydamping = 24016
sim_vortex_body_materialuniqueid = 25008
sim_vortex_body_normalangularaxisfriction = 24005
sim_vortex_body_normalangularaxisslide = 24022
sim_vortex_body_normalangularaxisslip = 24027
sim_vortex_body_normalangularaxisstaticfrictionscale = 24010
sim_vortex_body_normalmangulararaxisfrictionmodel = 25005
sim_vortex_body_normangaxissameasprimangaxis = 26008
sim_vortex_body_primangulararaxisfrictionmodel = 25003
sim_vortex_body_primangularaxisfriction = 24003
sim_vortex_body_primangularaxisslide = 24020
sim_vortex_body_primangularaxisslip = 24025
sim_vortex_body_primangularaxisstaticfrictionscale = 24008
sim_vortex_body_primaxisvectorx = 24034
sim_vortex_body_primaxisvectory = 24035
sim_vortex_body_primaxisvectorz = 24036
sim_vortex_body_primlinearaxisfriction = 24001
sim_vortex_body_primlinearaxisfrictionmodel = 25001
sim_vortex_body_primlinearaxisslide = 24018
sim_vortex_body_primlinearaxisslip = 24023
sim_vortex_body_primlinearaxisstaticfrictionscale = 24006
sim_vortex_body_pureshapesasconvex = 26001
sim_vortex_body_randomshapesasterrain = 26003
sim_vortex_body_restitution = 24013
sim_vortex_body_restitutionthreshold = 24014
sim_vortex_body_secangaxissameasprimangaxis = 26007
sim_vortex_body_secangularaxisfriction = 24004
sim_vortex_body_secangularaxisslide = 24021
sim_vortex_body_secangularaxisslip = 24026
sim_vortex_body_secangularaxisstaticfrictionscale = 24009
sim_vortex_body_seclinaxissameasprimlinaxis = 26006
sim_vortex_body_seclinearaxisfriction = 24002
sim_vortex_body_seclinearaxisfrictionmodel = 25002
sim_vortex_body_seclinearaxisslide = 24019
sim_vortex_body_seclinearaxisslip = 24024
sim_vortex_body_seclinearaxisstaticfrictionscale = 24007
sim_vortex_body_secmangulararaxisfrictionmodel = 25004
sim_vortex_body_skinthickness = 24032
sim_vortex_bodyfrictionmodel_box = 0
sim_vortex_bodyfrictionmodel_neutral = 5
sim_vortex_bodyfrictionmodel_none = 6
sim_vortex_bodyfrictionmodel_prophigh = 3
sim_vortex_bodyfrictionmodel_proplow = 2
sim_vortex_bodyfrictionmodel_scaledbox = 1
sim_vortex_bodyfrictionmodel_scaledboxfast = 4
sim_vortex_global_autosleep = 20001
sim_vortex_global_bitcoded = 19001
sim_vortex_global_bool_end = 20003
sim_vortex_global_bool_start = 20000
sim_vortex_global_constraintangularcompliance = 18007
sim_vortex_global_constraintangulardamping = 18008
sim_vortex_global_constraintangularkineticloss = 18009
sim_vortex_global_constraintlinearcompliance = 18004
sim_vortex_global_constraintlineardamping = 18005
sim_vortex_global_constraintlinearkineticloss = 18006
sim_vortex_global_contacttolerance = 18003
sim_vortex_global_float_end = 18010
sim_vortex_global_float_start = 18000
sim_vortex_global_int_end = 19002
sim_vortex_global_int_start = 19000
sim_vortex_global_internalscalingfactor = 18002
sim_vortex_global_multithreading = 20002
sim_vortex_global_stepsize = 18001
sim_vortex_joint_a0damping = 21032
sim_vortex_joint_a0frictioncoeff = 21033
sim_vortex_joint_a0frictionloss = 21035
sim_vortex_joint_a0frictionmaxforce = 21034
sim_vortex_joint_a0loss = 21030
sim_vortex_joint_a0stiffness = 21031
sim_vortex_joint_a1damping = 21038
sim_vortex_joint_a1frictioncoeff = 21039
sim_vortex_joint_a1frictionloss = 21041
sim_vortex_joint_a1frictionmaxforce = 21040
sim_vortex_joint_a1loss = 21036
sim_vortex_joint_a1stiffness = 21037
sim_vortex_joint_a2damping = 21044
sim_vortex_joint_a2frictioncoeff = 21045
sim_vortex_joint_a2frictionloss = 21047
sim_vortex_joint_a2frictionmaxforce = 21046
sim_vortex_joint_a2loss = 21042
sim_vortex_joint_a2stiffness = 21043
sim_vortex_joint_bitcoded = 22001
sim_vortex_joint_bool_end = 23003
sim_vortex_joint_bool_start = 23000
sim_vortex_joint_dependencyfactor = 21048
sim_vortex_joint_dependencyoffset = 21049
sim_vortex_joint_dependentobjectid = 22006
sim_vortex_joint_float_end = 21050
sim_vortex_joint_float_start = 21000
sim_vortex_joint_frictionenabledbc = 22003
sim_vortex_joint_frictionproportionalbc = 22004
sim_vortex_joint_int_end = 22007
sim_vortex_joint_int_start = 22000
sim_vortex_joint_lowerlimitdamping = 21001
sim_vortex_joint_lowerlimitmaxforce = 21007
sim_vortex_joint_lowerlimitrestitution = 21005
sim_vortex_joint_lowerlimitstiffness = 21003
sim_vortex_joint_motorconstraintfrictioncoeff = 21009
sim_vortex_joint_motorconstraintfrictionloss = 21011
sim_vortex_joint_motorconstraintfrictionmaxforce = 21010
sim_vortex_joint_motorfrictionenabled = 23001
sim_vortex_joint_objectid = 22005
sim_vortex_joint_p0damping = 21014
sim_vortex_joint_p0frictioncoeff = 21015
sim_vortex_joint_p0frictionloss = 21017
sim_vortex_joint_p0frictionmaxforce = 21016
sim_vortex_joint_p0loss = 21012
sim_vortex_joint_p0stiffness = 21013
sim_vortex_joint_p1damping = 21020
sim_vortex_joint_p1frictioncoeff = 21021
sim_vortex_joint_p1frictionloss = 21023
sim_vortex_joint_p1frictionmaxforce = 21022
sim_vortex_joint_p1loss = 21018
sim_vortex_joint_p1stiffness = 21019
sim_vortex_joint_p2damping = 21026
sim_vortex_joint_p2frictioncoeff = 21027
sim_vortex_joint_p2frictionloss = 21029
sim_vortex_joint_p2frictionmaxforce = 21028
sim_vortex_joint_p2loss = 21024
sim_vortex_joint_p2stiffness = 21025
sim_vortex_joint_proportionalmotorfriction = 23002
sim_vortex_joint_relaxationenabledbc = 22002
sim_vortex_joint_upperlimitdamping = 21002
sim_vortex_joint_upperlimitmaxforce = 21008
sim_vortex_joint_upperlimitrestitution = 21006
sim_vortex_joint_upperlimitstiffness = 21004
simrml_disable_extremum_motion_states_calc = 8
simrml_keep_current_vel_if_fallback_strategy = 16
simrml_keep_target_vel = 0
simrml_no_sync = 3
simrml_only_phase_sync = 2
simrml_only_time_sync = 1
simrml_phase_sync_if_possible = 0
simrml_recompute_trajectory = 4
simros_strmcmd_add_status_bar_message = 2049
simros_strmcmd_append_string_signal = 14344
simros_strmcmd_auxiliary_console_print = 6145
simros_strmcmd_clear_float_signal = 14337
simros_strmcmd_clear_integer_signal = 14338
simros_strmcmd_clear_string_signal = 14339
simros_strmcmd_get_and_clear_string_signal = 12293
simros_strmcmd_get_array_parameter = 4097
simros_strmcmd_get_boolean_parameter = 4098
simros_strmcmd_get_depth_sensor_data = 4118
simros_strmcmd_get_dialog_result = 4099
simros_strmcmd_get_float_signal = 12289
simros_strmcmd_get_floating_parameter = 4100
simros_strmcmd_get_info = 2
simros_strmcmd_get_integer_parameter = 4101
simros_strmcmd_get_integer_signal = 12290
simros_strmcmd_get_joint_state = 4102
simros_strmcmd_get_laser_scanner_data = 4116
simros_strmcmd_get_object_float_parameter = 8194
simros_strmcmd_get_object_group_data = 8199
simros_strmcmd_get_object_int_parameter = 8195
simros_strmcmd_get_object_parent = 4103
simros_strmcmd_get_object_pose = 8193
simros_strmcmd_get_object_selection = 1
simros_strmcmd_get_objects = 4104
simros_strmcmd_get_odom_data = 4117
simros_strmcmd_get_range_finder_data = 4115
simros_strmcmd_get_string_parameter = 4105
simros_strmcmd_get_string_signal = 12291
simros_strmcmd_get_transform = 8198
simros_strmcmd_get_twist_status = 16385
simros_strmcmd_get_ui_button_property = 8196
simros_strmcmd_get_ui_event_button = 4106
simros_strmcmd_get_ui_slider = 8197
simros_strmcmd_get_vision_sensor_depth_buffer = 4107
simros_strmcmd_get_vision_sensor_image = 4108
simros_strmcmd_get_vision_sensor_info = 4114
simros_strmcmd_read_collision = 4109
simros_strmcmd_read_distance = 4110
simros_strmcmd_read_force_sensor = 4111
simros_strmcmd_read_proximity_sensor = 4112
simros_strmcmd_read_vision_sensor = 4113
simros_strmcmd_receive_data_from_script_function = 16386
simros_strmcmd_reserved1 = 12292
simros_strmcmd_reserved2 = 14343
simros_strmcmd_send_data_to_script_function = 18433
simros_strmcmd_set_array_parameter = 6146
simros_strmcmd_set_boolean_parameter = 6147
simros_strmcmd_set_float_signal = 14340
simros_strmcmd_set_floating_parameter = 6148
simros_strmcmd_set_integer_parameter = 6149
simros_strmcmd_set_integer_signal = 14341
simros_strmcmd_set_joint_force = 6150
simros_strmcmd_set_joint_position = 6151
simros_strmcmd_set_joint_state = 2051
simros_strmcmd_set_joint_target_position = 6152
simros_strmcmd_set_joint_target_velocity = 6153
simros_strmcmd_set_joint_trajectory = 14345
simros_strmcmd_set_joy_sensor = 6155
simros_strmcmd_set_object_float_parameter = 10241
simros_strmcmd_set_object_int_parameter = 10242
simros_strmcmd_set_object_pose = 10243
simros_strmcmd_set_object_position = 10244
simros_strmcmd_set_object_quaternion = 10245
simros_strmcmd_set_object_selection = 2050
simros_strmcmd_set_string_signal = 14342
simros_strmcmd_set_twist_command = 6156
simros_strmcmd_set_ui_button_label = 10246
simros_strmcmd_set_ui_button_property = 10247
simros_strmcmd_set_ui_slider = 10248
simros_strmcmd_set_vision_sensor_image = 6154
simros_strmcmdint_start = 4096
simros_strmcmdint_subscriber_start = 6144
simros_strmcmdintint_start = 8192
simros_strmcmdintint_subscriber_start = 10240
simros_strmcmdintstring_start = 16384
simros_strmcmdintstring_subscriber_start = 18432
simros_strmcmdnull_start = 0
simros_strmcmdnull_subscriber_start = 2048
simros_strmcmdreserved_start = 20480
simros_strmcmdstring_start = 12288
simros_strmcmdstring_subscriber_start = 14336
simx_cmd1string_custom_start = 14336
simx_cmd1string_start = 12288
simx_cmd4bytes2strings_end = 13568
simx_cmd4bytes2strings_start = 13312
simx_cmd4bytes_custom_start = 6144
simx_cmd4bytes_start = 4096
simx_cmd8bytes_custom_start = 10240
simx_cmd8bytes_start = 8192
simx_cmd_add_statusbar_message = 12296
simx_cmd_append_string_signal = 12310
simx_cmd_aux_console_close = 4116
simx_cmd_aux_console_open = 12297
simx_cmd_aux_console_print = 4117
simx_cmd_aux_console_show = 4118
simx_cmd_break_force_sensor = 4112
simx_cmd_call_script_function = 13313
simx_cmd_clear_float_signal = 12301
simx_cmd_clear_integer_signal = 12302
simx_cmd_clear_string_signal = 12303
simx_cmd_close_scene = 5
simx_cmd_copy_paste_objects = 4142
simx_cmd_create_dummy = 9
simx_cmd_display_dialog = 12300
simx_cmd_end_dialog = 4139
simx_cmd_erase_file = 12294
simx_cmd_get_and_clear_string_signal = 12311
simx_cmd_get_array_parameter = 4125
simx_cmd_get_boolean_parameter = 4127
simx_cmd_get_collection_handle = 12313
simx_cmd_get_collision_handle = 12298
simx_cmd_get_dialog_input = 4140
simx_cmd_get_dialog_result = 4141
simx_cmd_get_distance_handle = 12299
simx_cmd_get_float_signal = 12304
simx_cmd_get_floating_parameter = 4131
simx_cmd_get_integer_parameter = 4129
simx_cmd_get_integer_signal = 12305
simx_cmd_get_joint_force = 4109
simx_cmd_get_joint_matrix = 4106
simx_cmd_get_joint_max_force = 4152
simx_cmd_get_joint_position = 4097
simx_cmd_get_last_errors = 4
simx_cmd_get_model_property = 4148
simx_cmd_get_object_child = 8203
simx_cmd_get_object_float_parameter = 8199
simx_cmd_get_object_group_data = 8204
simx_cmd_get_object_handle = 12289
simx_cmd_get_object_int_parameter = 8200
simx_cmd_get_object_orientation = 4120
simx_cmd_get_object_orientation2 = 8205
simx_cmd_get_object_parent = 4114
simx_cmd_get_object_position = 4121
simx_cmd_get_object_position2 = 8206
simx_cmd_get_object_quaternion = 10241
simx_cmd_get_object_selection = 6
simx_cmd_get_object_velocity = 4150
simx_cmd_get_objects = 4138
simx_cmd_get_string_parameter = 4133
simx_cmd_get_string_signal = 12306
simx_cmd_get_ui_button_property = 8196
simx_cmd_get_ui_event_button = 8195
simx_cmd_get_ui_handle = 12295
simx_cmd_get_ui_slider = 8193
simx_cmd_get_vision_sensor_depth_buffer = 4119
simx_cmd_get_vision_sensor_image_bw = 4099
simx_cmd_get_vision_sensor_image_rgb = 4100
simx_cmd_kill_connection = 10
simx_cmd_load_model = 12291
simx_cmd_load_scene = 12290
simx_cmd_load_ui = 12293
simx_cmd_read_collision = 4134
simx_cmd_read_distance = 4135
simx_cmd_read_force_sensor = 4111
simx_cmd_read_proximity_sensor = 4105
simx_cmd_read_string_stream = 12312
simx_cmd_read_vision_sensor = 4113
simx_cmd_remove_model = 4151
simx_cmd_remove_object = 4136
simx_cmd_remove_ui = 4137
simx_cmd_reserved1 = 7
simx_cmd_reserved2 = 8
simx_cmd_set_array_parameter = 4126
simx_cmd_set_boolean_parameter = 4128
simx_cmd_set_float_signal = 12307
simx_cmd_set_floating_parameter = 4132
simx_cmd_set_integer_parameter = 4130
simx_cmd_set_integer_signal = 12308
simx_cmd_set_joint_force = 4110
simx_cmd_set_joint_position = 4098
simx_cmd_set_joint_target_position = 4108
simx_cmd_set_joint_target_velocity = 4104
simx_cmd_set_model_property = 4149
simx_cmd_set_object_float_parameter = 8201
simx_cmd_set_object_int_parameter = 8202
simx_cmd_set_object_orientation = 4122
simx_cmd_set_object_parent = 4124
simx_cmd_set_object_position = 4123
simx_cmd_set_object_quaternion = 6145
simx_cmd_set_object_selection = 4143
simx_cmd_set_spherical_joint_matrix = 4107
simx_cmd_set_string_signal = 12309
simx_cmd_set_ui_button_label = 8198
simx_cmd_set_ui_button_property = 8197
simx_cmd_set_ui_slider = 8194
simx_cmd_set_vision_sensor_image_bw = 4101
simx_cmd_set_vision_sensor_image_rgb = 4102
simx_cmd_spotcanbeused1 = 4144
simx_cmd_spotcanbeused2 = 4145
simx_cmd_spotcanbeused3 = 4146
simx_cmd_spotcanbeused4 = 4147
simx_cmd_spotcanbeused5 = 4115
simx_cmd_start_pause_stop_simulation = 4103
simx_cmd_synchronous_disable = 2
simx_cmd_synchronous_enable = 1
simx_cmd_synchronous_next = 3
simx_cmd_transfer_file = 12292
simx_cmd_write_string_stream = 12310
simx_cmdmask = 65535
simx_cmdnull_custom_start = 2048
simx_cmdnull_start = 0
simx_cmdreserved_start = 16384
